name: Lock Old Threads

on:
  schedule:
    - cron: '42 4 * * 1'
  workflow_dispatch:

permissions:
  issues: write
  pull-requests: write
  discussions: write

concurrency:
  group: lock-threads

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - uses: JC5/lock-threads@v6
        with:
          github-token: ${{ github.token }}
          issue-inactive-days: '30'
          issue-lock-reason: 'resolved'
          pr-inactive-days: '30'
          pr-lock-reason: 'resolved'
          discussion-inactive-days: '30'
          log-output: true
